language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-wp-bones' ]; then cd .. && eval "mv $currentfolder generator-wp-bones" && cd generator-wp-bones; fi

